name: Coverage
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2  
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'
      - run: npm run clean
      - run: npm run compile
      - name: slither-static-analysis
        continue-on-error: true
        uses: luisfontes19/slither-static-analysis-action@v0.3.4
        with:
          run-npm-install: false
          slither-params: --solc-remaps @openzeppelin/=$(pwd)/node_modules/@openzeppelin/ --filter-paths "./contracts/mock" --detect suicidal,uninitialized-state,msg-value-loop,unchecked-transfer,reentrancy-eth,enum-conversion,erc20-interface,erc721-interface,reentrancy-no-eth,unchecked-lowlevel,unchecked-send,dead-code,reentrancy-unlimited-gas 
          projectPath: contracts
      - run: npm run coverage
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - uses: codecov/codecov-action@v2