name: Dev
on:
  push:
    branches:
      - dev
  pull_request:
      branches:
      - dev
      types: [closed]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: modules-
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install 
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn run pre-commit 
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn run coverage
      - run: yarn run coverage
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - uses: codecov/codecov-action@v2

  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: modules-
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: pip3 install slither-analyzer

      - name: Summary of static analysis
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: yarn run slither
    